# Generated by Django 6.0.4 on 2026-05-04 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(choices=[('pizza', 'Пицца'), ('pasta', 'Паста'), ('steak', 'Стейк'), ('salad', 'Салат'), ('dessert', 'Десерт'), ('drink', 'Напиток')], max_length=20, verbose_name='Категория')),
                ('price', models.PositiveIntegerField(verbose_name='Цена, ₸')),
                ('featured', models.BooleanField(default=False, verbose_name='Популярное')),
                ('active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('img', models.URLField(blank=True, max_length=600, verbose_name='Фото URL')),
                ('name_kz', models.CharField(max_length=160, verbose_name='Название KZ')),
                ('name_ru', models.CharField(max_length=160, verbose_name='Название RU')),
                ('name_en', models.CharField(max_length=160, verbose_name='Название EN')),
                ('desc_kz', models.TextField(blank=True, verbose_name='Описание KZ')),
                ('desc_ru', models.TextField(blank=True, verbose_name='Описание RU')),
                ('desc_en', models.TextField(blank=True, verbose_name='Описание EN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Позиция меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Принят'), ('confirmed', 'Подтвержден'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='Сумма, ₸')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('unit_price', models.PositiveIntegerField(verbose_name='Цена за шт., ₸')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.order')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=160, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
