# Generated by Django 6.0.4 on 2026-05-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_reservation_reservationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма скидки, ₸'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Скидка, %'),
        ),
    ]
