# Generated by Django 6.0.4 on 2026-05-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_order_discount_amount_order_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой'), ('kaspi', 'Kaspi')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
